In [45]:
import pandas as pd
import dotenv
import os
from app.model_handler import ModelHandler

user_data_path = os.getenv('ML_MODEL_USER_DATA_PATH')
common_data_path = os.getenv('ML_MODEL_COMMON_DATA_PATH')

user_recs = pd.read_parquet(user_data_path, columns=['user_id', 'item_id', 'rank'])
user_recs = user_recs.set_index('user_id')
display(user_recs)

common_recs = pd.read_parquet(common_data_path)
display(common_recs)

          item_id  rank
user_id
4        38646012     1
4        32851197     2
4        60292250     3
4        38903142     4
4        24327639     5
...           ...   ...
1374582  52395280    96
1374582  33308971    97
1374582   9167465    98
1374582  37641523    99
1374582  39946957   100

[53670600 rows x 2 columns]

           count
item_id
53404     110026
33311009  101076
178529    100866
35505245   95523
24692821   84153
...          ...
68562711   47588
75944934   47536
75642961   47438
29175370   47320
68348389   47225

[100 rows x 1 columns]

In [53]:
user_recs.loc[4]['item_id'][:5].tolist()

[38646012, 32851197, 60292250, 38903142, 24327639]

In [42]:
common_recs[:5].index.tolist()

[53404, 33311009, 178529, 35505245, 24692821]

In [54]:
a = []
if len(a) == 0:
    print('is 0')

is 0