# Offline recs service

In [45]:
import pandas as pd
import dotenv
import os
from app.model_handler import ModelHandler

user_data_path = os.getenv('ML_MODEL_USER_DATA_PATH')
common_data_path = os.getenv('ML_MODEL_COMMON_DATA_PATH')

user_recs = pd.read_parquet(user_data_path, columns=['user_id', 'item_id', 'rank'])
user_recs = user_recs.set_index('user_id')
display(user_recs)

common_recs = pd.read_parquet(common_data_path)
display(common_recs)

          item_id  rank
user_id
4        38646012     1
4        32851197     2
4        60292250     3
4        38903142     4
4        24327639     5
...           ...   ...
1374582  52395280    96
1374582  33308971    97
1374582   9167465    98
1374582  37641523    99
1374582  39946957   100

[53670600 rows x 2 columns]

           count
item_id
53404     110026
33311009  101076
178529    100866
35505245   95523
24692821   84153
...          ...
68562711   47588
75944934   47536
75642961   47438
29175370   47320
68348389   47225

[100 rows x 1 columns]

In [53]:
user_recs.loc[4]['item_id'][:5].tolist()

[38646012, 32851197, 60292250, 38903142, 24327639]

In [42]:
common_recs[:5].index.tolist()

[53404, 33311009, 178529, 35505245, 24692821]

# Event store service

In [29]:
event_store = {}

user_id = 11
item_id = 22

user_events = event_store[user_id] if user_id in event_store.keys() else []
user_events.insert(0, item_id)
event_store[user_id] = user_events

event_store

{11: [22]}

In [30]:
user_events

[22]

In [31]:
event_store.keys()

dict_keys([11])

In [ ]:
user_id = 11
item_id = 33

user_events = event_store[user_id] if user_id in event_store.keys() else []
user_events.insert(0, item_id)
event_store[user_id] = user_events

event_store

{11: [33, 33, 44, 33, 22]}

In [33]:
user_events.insert(0, 44)

In [34]:
user_events

[44, 33, 22]

In [8]:
from random import randint

params = {
    'user_id': randint(0, 10),  #randint(0, 1320000), 
    'item_id': randint(0, 10) #randint(0, 930000)
}    

list(params.items())[0]

('user_id', 9)

# Content service

In [2]:
import pandas as pd

data_path = 'data/recsys/similar.parquet'
#columns = 

similar_items = pd.read_parquet(data_path) #, columns=data_columns)
similar_items = similar_items.set_index('item_id')

similar_items

           sim_item_id     score
item_id
26                  26  1.000000
26            20111365  0.841317
26            27419607  0.826416
26            26343802  0.820421
26             1293112  0.803062
...                ...       ...
101521819     92503045  0.849149
101521819     97820398  0.848006
101521819    101084646  0.844078
101521819     94735558  0.837228
101521819     97241633  0.830391

[9326640 rows x 2 columns]

In [8]:
item_id = 26
top_k = 100
items = similar_items.loc[item_id]['sim_item_id'][:top_k].tolist()
items

[26,
 20111365,
 27419607,
 26343802,
 1293112,
 21846409,
 13469947,
 534678,
 20034028,
 107536]

In [ ]:
similar_items.sample(100).index.tolist()